class ProviderData {
  final String name;
  final double rating;
  final int completedWorks;
  final String location;
  final String imageUrl;
  final String category;
  final String profession;
  final List<String> subCategories;
  bool isAvailable;

  ProviderData({
    required this.name,
    required this.rating,
    required this.completedWorks,
    required this.location,
    required this.imageUrl,
    required this.category,
    required this.profession,
    required this.subCategories,
    this.isAvailable = false,
  });
}

List<ProviderData> providers = [
  ProviderData(
    name: 'John Doe',
    rating: 4.5,
    completedWorks: 120,
    location: 'Colombo',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'House Cleaning',
    profession: 'Cleaner',
    subCategories: [
      'Regular Cleaning',
      'Carpet Cleaning',
      'Window Cleaning',
      'Upholstery Cleaning'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Jane Doe',
    rating: 4.2,
    completedWorks: 90,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'Plumbing Services',
    profession: 'Plumber',
    subCategories: [
      'Leak Repair',
      'Pipe Installation and and Repair',
      'Faucet and Sink Repair',
      'Water heater Repair and Installation',
      'Sewer Line Services'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Alice Smith',
    rating: 4.8,
    completedWorks: 150,
    location: 'Galle',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'Carpentry Services',
    profession: 'Carpenter',
    subCategories: [
      'Custom Cabinetry',
      'Wood Flooring Installation',
      'Trim and Molding Installation',
      'Deck Building and Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Bob Brown',
    rating: 4.6,
    completedWorks: 110,
    location: 'Jaffna',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'Masonry',
    profession: 'Mason',
    subCategories: ['Masonry Repairs'],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Charlie Green',
    rating: 4.4,
    completedWorks: 100,
    location: 'Matara',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Electrical Services',
    profession: 'Electrician',
    subCategories: [
      'Electrical Wiring and Rewiring',
      'Circuit Breaker Installation',
      'Electrical Panel Upgrades',
      'Lightning Installation',
      'Generator Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'David White',
    rating: 4.7,
    completedWorks: 140,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'Mechanic Services',
    profession: 'Mechanic',
    subCategories: [
      'Engine Diagnostic and Repair',
      'Breake Services',
      'Transmission Repair',
      'Tire Services and Alignment',
      'Routine Maintenance',
      'Bodywork and collision Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Eve Black',
    rating: 4.3,
    completedWorks: 80,
    location: 'Badulla',
    imageUrl: 'assets/images/profile-7.jpg',
    category: 'Gardening Services',
    profession: 'Gardener',
    subCategories: [
      'Lawn Care and Moving',
      'Tree Trimming nd Pruning',
      'Planting and Weeding',
      'Garden Design and Landscaping'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Frank Grey',
    rating: 4.9,
    completedWorks: 160,
    location: 'Jaffna',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'Appliance Repair',
    profession: 'Appliance Technician',
    subCategories: [
      'Refrigerator Repair',
      'Washer and Dryer Repair',
      'Small Appliance Repair',
      'Oven and Stove Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Grace Brown',
    rating: 4.1,
    completedWorks: 70,
    location: 'Colombo',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'Pest Control',
    profession: 'Pest Control Technician',
    subCategories: [
      'Termite Control',
      'Rodent Control',
      'Insect Extermination (ants, cockroaches)',
      'Bed Bug Treatment'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Henry Green',
    rating: 4.0,
    completedWorks: 60,
    location: 'Galle',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'Roofing Repair',
    profession: 'Roofer',
    subCategories: [
      'Roof Installtion and Repair',
      'Roof Maintenance',
      'Roof Replacement',
      'Roof Inspections'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Ivy White',
    rating: 4.2,
    completedWorks: 90,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'Gutter Repair',
    profession: 'Gutter Technician',
    subCategories: [
      'Gutter Installation and Repair',
      'Gutter Cleaning',
      'Gutter Maintenance',
      'Gutter Guard Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Jack Black',
    rating: 4.4,
    completedWorks: 100,
    location: 'Matara',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Window and Door Installations',
    profession: 'Window and Door Installer',
    subCategories: [
      'Window Replacement and Installation',
      'Door Replacement and Installation',
      'Glass Repair and Replacement',
      'Door Hardware Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Kelly Grey',
    rating: 4.6,
    completedWorks: 110,
    location: 'Negombo',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'HVAC Services',
    profession: 'HVAC Technician',
    subCategories: [
      'Heating System repair and Installation',
      'Air Conditioning Repair and Installation',
      'HVAC System Maintenance',
      'Duct Cleaning and Sealing',
      'Thermostat Installation and Repair',
      'Ventilation System Repair',
      'System upgrade and Replacement'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Larry Brown',
    rating: 4.8,
    completedWorks: 150,
    location: 'Anuradhapura',
    imageUrl: 'assets/images/profile-7.jpg',
    category: 'Elder Care Services',
    profession: 'Elder Caregiver',
    subCategories: [
      'Personal Care Assistance',
      'Medication Management',
      'Companionship and Social Interaction',
      'Meal Preparation',
      'Respite Care'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Mandy Green',
    rating: 4.5,
    completedWorks: 120,
    location: 'Kurunegala',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'Baby Care Services',
    profession: 'Babysitter',
    subCategories: [
      'Infant Care',
      'Daytime Babysitting',
      'Overnight Babysitting',
      'Meal Preparation for Children',
      'Educational and Play Activities'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Nancy White',
    rating: 4.7,
    completedWorks: 140,
    location: 'Batticaloa',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'House Cleaning',
    profession: 'Cleaner',
    subCategories: [
      'Regular Cleaning',
      'Carpet Cleaning',
      'Window Cleaning',
      'Upholstery Cleaning'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Oliver Black',
    rating: 4.9,
    completedWorks: 160,
    location: 'Ratnapura',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'Plumbing Services',
    profession: 'Plumber',
    subCategories: [
      'Leak Repair',
      'Pipe Installation and and Repair',
      'Faucet and Sink Repair',
      'Water heater Repair and Installation',
      'Sewer Line Services'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Peter Grey',
    rating: 4.3,
    completedWorks: 80,
    location: 'Trincomalee',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'Carpentry Services',
    profession: 'Carpenter',
    subCategories: [
      'Custom Cabinetry',
      'Wood Flooring Installation',
      'Trim and Molding Installation',
      'Deck Building and Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Quincy Brown',
    rating: 4.1,
    completedWorks: 70,
    location: 'Kalutara',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Masonry',
    profession: 'Mason',
    subCategories: ['Masonry Repairs'],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Rose Green',
    rating: 4.0,
    completedWorks: 60,
    location: 'Kegalle',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'Electrical Services',
    profession: 'Electrician',
    subCategories: [
      'Electrical Wiring and Rewiring',
      'Circuit Breaker Installation',
      'Electrical Panel Upgrades',
      'Lightning Installation',
      'Generator Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Sam White',
    rating: 4.2,
    completedWorks: 90,
    location: 'Matale',
    imageUrl: 'assets/images/profile-7.jpg',
    category: 'Mechanic Services',
    profession: 'Mechanic',
    subCategories: [
      'Engine Diagnostic and Repair',
      'Breake Services',
      'Transmission Repair',
      'Tire Services and Alignment',
      'Routine Maintenance',
      'Bodywork and collision Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Tom Black',
    rating: 4.4,
    completedWorks: 100,
    location: 'Puttalam',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'Gardening Services',
    profession: 'Gardener',
    subCategories: [
      'Lawn Care and Moving',
      'Tree Trimming nd Pruning',
      'Planting and Weeding',
      'Garden Design and Landscaping'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Uma Grey',
    rating: 4.6,
    completedWorks: 110,
    location: 'Chilaw',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'Appliance Repair',
    profession: 'Appliance Technician',
    subCategories: [
      'Refrigerator Repair',
      'Washer and Dryer Repair',
      'Small Appliance Repair',
      'Oven and Stove Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Vince Brown',
    rating: 4.8,
    completedWorks: 150,
    location: 'Badulla',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'Pest Control',
    profession: 'Pest Control Technician',
    subCategories: [
      'Termite Control',
      'Rodent Control',
      'Insect Extermination (ants, cockroaches)',
      'Bed Bug Treatment'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Wendy Green',
    rating: 4.5,
    completedWorks: 120,
    location: 'Anuradhapura',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'Roofing Repair',
    profession: 'Roofer',
    subCategories: [
      'Roof Installtion and Repair',
      'Roof Maintenance',
      'Roof Replacement',
      'Roof Inspections'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Xavier White',
    rating: 4.7,
    completedWorks: 140,
    location: 'Negombo',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Gutter Repair',
    profession: 'Gutter Technician',
    subCategories: [
      'Gutter Installation and Repair',
      'Gutter Cleaning',
      'Gutter Maintenance',
      'Gutter Guard Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Yvonne Black',
    rating: 4.9,
    completedWorks: 160,
    location: 'Kurunegala',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'Window and Door Installations',
    profession: 'Window and Door Installer',
    subCategories: [
      'Window Replacement and Installation',
      'Door Replacement and Installation',
      'Glass Repair and Replacement',
      'Door Hardware Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Zack Grey',
    rating: 4.3,
    completedWorks: 80,
    location: 'Batticaloa',
    imageUrl: 'assets/images/profile-7.jpg',
    category: 'HVAC Services',
    profession: 'HVAC Technician',
    subCategories: [
      'Heating System repair and Installation',
      'Air Conditioning Repair and Installation',
      'HVAC System Maintenance',
      'Duct Cleaning and Sealing',
      'Thermostat Installation and Repair',
      'Ventilation System Repair',
      'System upgrade and Replacement'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Adam White',
    rating: 4.1,
    completedWorks: 70,
    location: 'Colombo',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'Elder Care Services',
    profession: 'Elder Caregiver',
    subCategories: [
      'Personal Care Assistance',
      'Medication Management',
      'Companionship and Social Interaction',
      'Meal Preparation',
      'Respite Care'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Betty Black',
    rating: 4.0,
    completedWorks: 60,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'Baby Care Services',
    profession: 'Babysitter',
    subCategories: [
      'Infant Care',
      'Daytime Babysitting',
      'Overnight Babysitting',
      'Meal Preparation for Children',
      'Educational and Play Activities'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Carl Green',
    rating: 4.2,
    completedWorks: 90,
    location: 'Galle',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'House Cleaning',
    profession: 'Cleaner',
    subCategories: [
      'Regular Cleaning',
      'Carpet Cleaning',
      'Window Cleaning',
      'Upholstery Cleaning'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Diana White',
    rating: 4.4,
    completedWorks: 100,
    location: 'Jaffna',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'Plumbing Services',
    profession: 'Plumber',
    subCategories: [
      'Leak Repair',
      'Pipe Installation and and Repair',
      'Faucet and Sink Repair',
      'Water heater Repair and Installation',
      'Sewer Line Services'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Ethan Black',
    rating: 4.6,
    completedWorks: 110,
    location: 'Matara',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Carpentry Services',
    profession: 'Carpenter',
    subCategories: [
      'Custom Cabinetry',
      'Wood Flooring Installation',
      'Trim and Molding Installation',
      'Deck Building and Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Fiona Grey',
    rating: 4.8,
    completedWorks: 150,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'Masonry',
    profession: 'Mason',
    subCategories: ['Masonry Repairs'],
    isAvailable: true,
  ),
  ProviderData(
    name: 'George Green',
    rating: 4.5,
    completedWorks: 120,
    location: 'Colombo',
    imageUrl: 'assets/images/profile-7.jpg',
    category: 'Electrical Services',
    profession: 'Electrician',
    subCategories: [
      'Electrical Wiring and Rewiring',
      'Circuit Breaker Installation',
      'Electrical Panel Upgrades',
      'Lightning Installation',
      'Generator Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Hannah White',
    rating: 4.7,
    completedWorks: 140,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'Mechanic Services',
    profession: 'Mechanic',
    subCategories: [
      'Engine Diagnostic and Repair',
      'Breake Services',
      'Transmission Repair',
      'Tire Services and Alignment',
      'Routine Maintenance',
      'Bodywork and collision Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Ian Black',
    rating: 4.3,
    completedWorks: 80,
    location: 'Badulla',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'Gardening Services',
    profession: 'Gardener',
    subCategories: [
      'Lawn Care and Moving',
      'Tree Trimming nd Pruning',
      'Planting and Weeding',
      'Garden Design and Landscaping'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Jenny Grey',
    rating: 4.9,
    completedWorks: 160,
    location: 'Jaffna',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'Appliance Repair',
    profession: 'Appliance Technician',
    subCategories: [
      'Refrigerator Repair',
      'Washer and Dryer Repair',
      'Small Appliance Repair',
      'Oven and Stove Repair'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Kevin Green',
    rating: 4.1,
    completedWorks: 70,
    location: 'Colombo',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'Pest Control',
    profession: 'Pest Control Technician',
    subCategories: [
      'Termite Control',
      'Rodent Control',
      'Insect Extermination (ants, cockroaches)',
      'Bed Bug Treatment'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Lily White',
    rating: 4.0,
    completedWorks: 60,
    location: 'Galle',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Roofing Repair',
    profession: 'Roofer',
    subCategories: [
      'Roof Installtion and Repair',
      'Roof Maintenance',
      'Roof Replacement',
      'Roof Inspections'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Mike Black',
    rating: 4.2,
    completedWorks: 90,
    location: 'Kandy',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'Gutter Repair',
    profession: 'Gutter Technician',
    subCategories: [
      'Gutter Installation and Repair',
      'Gutter Cleaning',
      'Gutter Maintenance',
      'Gutter Guard Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Nina Grey',
    rating: 4.4,
    completedWorks: 100,
    location: 'Matara',
    imageUrl: 'assets/images/profile-7.jpg',
    category: 'Window and Door Installations',
    profession: 'Window and Door Installer',
    subCategories: [
      'Window Replacement and Installation',
      'Door Replacement and Installation',
      'Glass Repair and Replacement',
      'Door Hardware Installation'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Oscar White',
    rating: 4.6,
    completedWorks: 110,
    location: 'Negombo',
    imageUrl: 'assets/images/profile-1.jpg',
    category: 'HVAC Services',
    profession: 'HVAC Technician',
    subCategories: [
      'Heating System repair and Installation',
      'Air Conditioning Repair and Installation',
      'HVAC System Maintenance',
      'Duct Cleaning and Sealing',
      'Thermostat Installation and Repair',
      'Ventilation System Repair',
      'System upgrade and Replacement'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Patty Black',
    rating: 4.8,
    completedWorks: 150,
    location: 'Anuradhapura',
    imageUrl: 'assets/images/profile-2.jpg',
    category: 'Elder Care Services',
    profession: 'Elder Caregiver',
    subCategories: [
      'Personal Care Assistance',
      'Medication Management',
      'Companionship and Social Interaction',
      'Meal Preparation',
      'Respite Care'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Quinn Green',
    rating: 4.5,
    completedWorks: 120,
    location: 'Kurunegala',
    imageUrl: 'assets/images/profile-3.jpg',
    category: 'Baby Care Services',
    profession: 'Babysitter',
    subCategories: [
      'Infant Care',
      'Daytime Babysitting',
      'Overnight Babysitting',
      'Meal Preparation for Children',
      'Educational and Play Activities'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Randy White',
    rating: 4.7,
    completedWorks: 140,
    location: 'Batticaloa',
    imageUrl: 'assets/images/profile-4.jpg',
    category: 'House Cleaning',
    profession: 'Cleaner',
    subCategories: [
      'Regular Cleaning',
      'Carpet Cleaning',
      'Window Cleaning',
      'Upholstery Cleaning'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Sally Black',
    rating: 4.9,
    completedWorks: 160,
    location: 'Ratnapura',
    imageUrl: 'assets/images/profile-5.jpg',
    category: 'Plumbing Services',
    profession: 'Plumber',
    subCategories: [
      'Leak Repair',
      'Pipe Installation and and Repair',
      'Faucet and Sink Repair',
      'Water heater Repair and Installation',
      'Sewer Line Services'
    ],
    isAvailable: true,
  ),
  ProviderData(
    name: 'Tim Grey',
    rating: 4.3,
    completedWorks: 80,
    location: 'Trincomalee',
    imageUrl: 'assets/images/profile-6.jpg',
    category: 'Carpentry Services',
    profession: 'Carpenter',
    subCategories: [
      'Custom Cabinetry',
      'Wood Flooring Installation',
      'Trim and Molding Installation',
      'Deck Building and Repair'
    ],
    isAvailable: true,
  ),
];
