const Map<String, List<String>> subCategories = {
  'House Cleaning': [
    'Regular Cleaning',
    'Carpet Cleaning',
    'Window Cleaning',
    'Upholstery Cleaning',
  ],
  'Plumbing Services': [
    'Leak Repair',
    'Pipe Installation and Repair',
    'Faucet and Sink Repair',
    'Water heater Repair and Installation',
    'Sewer Line Services',
  ],
  'Carpentry Services': [
    'Custom Cabinetry',
    'Wood Flooring Installation',
    'Trim and Molding Installation',
    'Deck Building and Repair',
  ],
  'Masonry Services': [
    'Masonry Repairs',
  ],
  'Electrical Services': [
    'Electrical Wiring and Rewiring',
    'Circuit Breaker Installation',
    'Electrical Panel Upgrades',
    'Lightning Installation',
    'Generator Installation',
  ],
  'Mechanic Services': [
    'Engine Diagnostic and Repair',
    'Breake Services',
    'Transmission Repair',
    'Tire Services and Alignment',
    'Routine Maintenance',
    'Bodywork and collision Repair',
  ],
  'Gardening Services': [
    'Lawn Care and Moving',
    'Tree Trimming and Pruning',
    'Planting and Weeding',
    'Garden Design and Landscaping',
  ],
  'Appliance Repair': [
    'Refrigerator Repair',
    'Washer and Dryer Repair',
    'Small Appliance Repair',
    'Oven and Stove Repair',
  ],
  'Pest Control': [
    'Termite Control',
    'Rodent Control',
    'Insect Extermination (ants, cockroaches)',
    'Bed Bug Treatment',
  ],
  'Roofing Repair': [
    'Roof Installtion and Repair',
    'Roof Maintenance',
    'Roof Replacement',
    'Roof Inspections',
  ],
  'Gutter Repair': [
    'Gutter Installation and Repair',
    'Gutter Cleaning',
    'Gutter Maintenance',
    'Gutter Guard Installation',
  ],
  'Door Installations': [
    'Window Replacement and Installation',
    'Door Replacement and Installation',
    'Glass Repair and Replacement',
    'Door Hardware Installation',
  ],
  'HVAC Services': [
    'Heating System repair and Installation',
    'Air Conditioning Repair and Installation',
    'HVAC System Maintenance',
    'Duct Cleaning and Sealing',
    'Thermostat Installation and Repair',
    'Ventilation System Repair',
    'System upgrade and Replacement',
  ],
  'Elder Care Services': [
    'Personal Care Assistance',
    'Medication Management',
    'Companionship and Social Interaction',
    'Meal Preparation',
    'Respite Care',
  ],
  'Baby Care Services': [
    'Infant Care',
    'Daytime Babysitting',
    'Overnight Babysitting',
    'Meal Preparation for Children',
    'Educational and Play Activities',
  ],
};
