// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPf46xQhVCTf_q_NSMBjPReAxNDNn8oc',
    appId: '1:375415547870:web:91c8fcbbf7c4dbde34df4f',
    messagingSenderId: '375415547870',
    projectId: 'seyoniauth',
    authDomain: 'seyoniauth.firebaseapp.com',
    storageBucket: 'seyoniauth.appspot.com',
    measurementId: 'G-1EYM1D3PZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOdp3RJKFN5T-nbNMcXpFDol-MFUFe-8',
    appId: '1:375415547870:android:4898ead38d17a44534df4f',
    messagingSenderId: '375415547870',
    projectId: 'seyoniauth',
    storageBucket: 'seyoniauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_n3VoTtKYBwjUixDt8ZVogsuJ2F8K0pA',
    appId: '1:375415547870:ios:23012544d249aeb734df4f',
    messagingSenderId: '375415547870',
    projectId: 'seyoniauth',
    storageBucket: 'seyoniauth.appspot.com',
    iosBundleId: 'com.example.seyoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_n3VoTtKYBwjUixDt8ZVogsuJ2F8K0pA',
    appId: '1:375415547870:ios:23012544d249aeb734df4f',
    messagingSenderId: '375415547870',
    projectId: 'seyoniauth',
    storageBucket: 'seyoniauth.appspot.com',
    iosBundleId: 'com.example.seyoni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcPf46xQhVCTf_q_NSMBjPReAxNDNn8oc',
    appId: '1:375415547870:web:9c28a83411047a5734df4f',
    messagingSenderId: '375415547870',
    projectId: 'seyoniauth',
    authDomain: 'seyoniauth.firebaseapp.com',
    storageBucket: 'seyoniauth.appspot.com',
    measurementId: 'G-Y847BZWX36',
  );
}
