const mongoose = require("./config/db"); // Ensure this points to your db.js file
const Provider = require("./models/providerModel");

const providers = [
  {
    name: "John Doe",
    rating: 4.5,
    completedWorks: 120,
    location: "Colombo",
    imageUrl: "assets/images/profile-1.jpg",
    category: "House Cleaning",
    profession: "Cleaner",
    subCategories: [
      "Regular Cleaning",
      "Carpet Cleaning",
      "Window Cleaning",
      "Upholstery Cleaning",
    ],
    isAvailable: true,
  },
  {
    name: "Jane Doe",
    rating: 4.2,
    completedWorks: 90,
    location: "Kandy",
    imageUrl: "assets/images/profile-2.jpg",
    category: "Plumbing Services",
    profession: "Plumber",
    subCategories: [
      "Leak Repair",
      "Pipe Installation and and Repair",
      "Faucet and Sink Repair",
      "Water heater Repair and Installation",
      "Sewer Line Services",
    ],
    isAvailable: true,
  },
  {
    name: "Alice Smith",
    rating: 4.8,
    completedWorks: 150,
    location: "Galle",
    imageUrl: "assets/images/profile-3.jpg",
    category: "Carpentry Services",
    profession: "Carpenter",
    subCategories: [
      "Custom Cabinetry",
      "Wood Flooring Installation",
      "Trim and Molding Installation",
      "Deck Building and Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Bob Brown",
    rating: 4.6,
    completedWorks: 110,
    location: "Jaffna",
    imageUrl: "assets/images/profile-4.jpg",
    category: "Masonry",
    profession: "Mason",
    subCategories: ["Masonry Repairs"],
    isAvailable: true,
  },
  {
    name: "Charlie Green",
    rating: 4.4,
    completedWorks: 100,
    location: "Matara",
    imageUrl: "assets/images/profile-5.jpg",
    category: "Electrical Services",
    profession: "Electrician",
    subCategories: [
      "Electrical Wiring and Rewiring",
      "Circuit Breaker Installation",
      "Electrical Panel Upgrades",
      "Lightning Installation",
      "Generator Installation",
    ],
    isAvailable: true,
  },
  {
    name: "David White",
    rating: 4.7,
    completedWorks: 140,
    location: "Kandy",
    imageUrl: "assets/images/profile-6.jpg",
    category: "Mechanic Services",
    profession: "Mechanic",
    subCategories: [
      "Engine Diagnostic and Repair",
      "Breake Services",
      "Transmission Repair",
      "Tire Services and Alignment",
      "Routine Maintenance",
      "Bodywork and collision Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Eve Black",
    rating: 4.3,
    completedWorks: 80,
    location: "Badulla",
    imageUrl: "assets/images/profile-7.jpg",
    category: "Gardening Services",
    profession: "Gardener",
    subCategories: [
      "Lawn Care and Moving",
      "Tree Trimming nd Pruning",
      "Planting and Weeding",
      "Garden Design and Landscaping",
    ],
    isAvailable: true,
  },
  {
    name: "Frank Grey",
    rating: 4.9,
    completedWorks: 160,
    location: "Jaffna",
    imageUrl: "assets/images/profile-1.jpg",
    category: "Appliance Repair",
    profession: "Appliance Technician",
    subCategories: [
      "Refrigerator Repair",
      "Washer and Dryer Repair",
      "Small Appliance Repair",
      "Oven and Stove Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Grace Brown",
    rating: 4.1,
    completedWorks: 70,
    location: "Colombo",
    imageUrl: "assets/images/profile-2.jpg",
    category: "Pest Control",
    profession: "Pest Control Technician",
    subCategories: [
      "Termite Control",
      "Rodent Control",
      "Insect Extermination (ants, cockroaches)",
      "Bed Bug Treatment",
    ],
    isAvailable: true,
  },
  {
    name: "Henry Green",
    rating: 4.0,
    completedWorks: 60,
    location: "Galle",
    imageUrl: "assets/images/profile-3.jpg",
    category: "Roofing Repair",
    profession: "Roofer",
    subCategories: [
      "Roof Installtion and Repair",
      "Roof Maintenance",
      "Roof Replacement",
      "Roof Inspections",
    ],
    isAvailable: true,
  },
  {
    name: "Ivy White",
    rating: 4.2,
    completedWorks: 90,
    location: "Kandy",
    imageUrl: "assets/images/profile-4.jpg",
    category: "Gutter Repair",
    profession: "Gutter Technician",
    subCategories: [
      "Gutter Installation and Repair",
      "Gutter Cleaning",
      "Gutter Maintenance",
      "Gutter Guard Installation",
    ],
    isAvailable: true,
  },
  {
    name: "Jack Black",
    rating: 4.4,
    completedWorks: 100,
    location: "Matara",
    imageUrl: "assets/images/profile-5.jpg",
    category: "Window and Door Installations",
    profession: "Window and Door Installer",
    subCategories: [
      "Window Replacement and Installation",
      "Door Replacement and Installation",
      "Glass Repair and Replacement",
      "Door Hardware Installation",
    ],
    isAvailable: true,
  },
  {
    name: "Kelly Grey",
    rating: 4.6,
    completedWorks: 110,
    location: "Negombo",
    imageUrl: "assets/images/profile-6.jpg",
    category: "HVAC Services",
    profession: "HVAC Technician",
    subCategories: [
      "Heating System repair and Installation",
      "Air Conditioning Repair and Installation",
      "HVAC System Maintenance",
      "Duct Cleaning and Sealing",
      "Thermostat Installation and Repair",
      "Ventilation System Repair",
      "System upgrade and Replacement",
    ],
    isAvailable: true,
  },
  {
    name: "Larry Brown",
    rating: 4.8,
    completedWorks: 150,
    location: "Anuradhapura",
    imageUrl: "assets/images/profile-7.jpg",
    category: "Elder Care Services",
    profession: "Elder Caregiver",
    subCategories: [
      "Personal Care Assistance",
      "Medication Management",
      "Companionship and Social Interaction",
      "Meal Preparation",
      "Respite Care",
    ],
    isAvailable: true,
  },
  {
    name: "Mandy Green",
    rating: 4.5,
    completedWorks: 120,
    location: "Kurunegala",
    imageUrl: "assets/images/profile-1.jpg",
    category: "Baby Care Services",
    profession: "Babysitter",
    subCategories: [
      "Infant Care",
      "Daytime Babysitting",
      "Overnight Babysitting",
      "Meal Preparation for Children",
      "Educational and Play Activities",
    ],
    isAvailable: true,
  },
  {
    name: "Nancy White",
    rating: 4.7,
    completedWorks: 140,
    location: "Batticaloa",
    imageUrl: "assets/images/profile-2.jpg",
    category: "House Cleaning",
    profession: "Cleaner",
    subCategories: [
      "Regular Cleaning",
      "Carpet Cleaning",
      "Window Cleaning",
      "Upholstery Cleaning",
    ],
    isAvailable: true,
  },
  {
    name: "Oliver Black",
    rating: 4.9,
    completedWorks: 160,
    location: "Ratnapura",
    imageUrl: "assets/images/profile-3.jpg",
    category: "Plumbing Services",
    profession: "Plumber",
    subCategories: [
      "Leak Repair",
      "Pipe Installation and and Repair",
      "Faucet and Sink Repair",
      "Water heater Repair and Installation",
      "Sewer Line Services",
    ],
    isAvailable: true,
  },
  {
    name: "Peter Grey",
    rating: 4.3,
    completedWorks: 80,
    location: "Trincomalee",
    imageUrl: "assets/images/profile-4.jpg",
    category: "Carpentry Services",
    profession: "Carpenter",
    subCategories: [
      "Custom Cabinetry",
      "Wood Flooring Installation",
      "Trim and Molding Installation",
      "Deck Building and Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Quincy Brown",
    rating: 4.1,
    completedWorks: 70,
    location: "Kalutara",
    imageUrl: "assets/images/profile-5.jpg",
    category: "Masonry",
    profession: "Mason",
    subCategories: ["Masonry Repairs"],
    isAvailable: true,
  },
  {
    name: "Rose Green",
    rating: 4.0,
    completedWorks: 60,
    location: "Kegalle",
    imageUrl: "assets/images/profile-6.jpg",
    category: "Electrical Services",
    profession: "Electrician",
    subCategories: [
      "Electrical Wiring and Rewiring",
      "Circuit Breaker Installation",
      "Electrical Panel Upgrades",
      "Lightning Installation",
      "Generator Installation",
    ],
    isAvailable: true,
  },
  {
    name: "Sam White",
    rating: 4.2,
    completedWorks: 90,
    location: "Matale",
    imageUrl: "assets/images/profile-7.jpg",
    category: "Mechanic Services",
    profession: "Mechanic",
    subCategories: [
      "Engine Diagnostic and Repair",
      "Breake Services",
      "Transmission Repair",
      "Tire Services and Alignment",
      "Routine Maintenance",
      "Bodywork and collision Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Tom Black",
    rating: 4.4,
    completedWorks: 100,
    location: "Puttalam",
    imageUrl: "assets/images/profile-1.jpg",
    category: "Gardening Services",
    profession: "Gardener",
    subCategories: [
      "Lawn Care and Moving",
      "Tree Trimming nd Pruning",
      "Planting and Weeding",
      "Garden Design and Landscaping",
    ],
    isAvailable: true,
  },
  {
    name: "Uma Grey",
    rating: 4.6,
    completedWorks: 110,
    location: "Chilaw",
    imageUrl: "assets/images/profile-2.jpg",
    category: "Appliance Repair",
    profession: "Appliance Technician",
    subCategories: [
      "Refrigerator Repair",
      "Washer and Dryer Repair",
      "Small Appliance Repair",
      "Oven and Stove Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Vince Brown",
    rating: 4.8,
    completedWorks: 150,
    location: "Badulla",
    imageUrl: "assets/images/profile-3.jpg",
    category: "Pest Control",
    profession: "Pest Control Technician",
    subCategories: [
      "Termite Control",
      "Rodent Control",
      "Insect Extermination (ants, cockroaches)",
      "Bed Bug Treatment",
    ],
    isAvailable: true,
  },
  {
    name: "Wendy Green",
    rating: 4.5,
    completedWorks: 120,
    location: "Anuradhapura",
    imageUrl: "assets/images/profile-4.jpg",
    category: "Roofing Repair",
    profession: "Roofer",
    subCategories: [
      "Roof Installtion and Repair",
      "Roof Maintenance",
      "Roof Replacement",
      "Roof Inspections",
    ],
    isAvailable: true,
  },
  {
    name: "Xavier White",
    rating: 4.7,
    completedWorks: 140,
    location: "Negombo",
    imageUrl: "assets/images/profile-5.jpg",
    category: "Gutter Repair",
    profession: "Gutter Technician",
    subCategories: [
      "Gutter Installation and Repair",
      "Gutter Cleaning",
      "Gutter Maintenance",
      "Gutter Guard Installation",
    ],
    isAvailable: true,
  },
  {
    name: "Yvonne Black",
    rating: 4.9,
    completedWorks: 160,
    location: "Kurunegala",
    imageUrl: "assets/images/profile-6.jpg",
    category: "Window and Door Installations",
    profession: "Window and Door Installer",
    subCategories: [
      "Window Replacement and Installation",
      "Door Replacement and Installation",
      "Glass Repair and Replacement",
      "Door Hardware Installation",
    ],
    isAvailable: true,
  },
  {
    name: "Zack Grey",
    rating: 4.3,
    completedWorks: 80,
    location: "Batticaloa",
    imageUrl: "assets/images/profile-7.jpg",
    category: "HVAC Services",
    profession: "HVAC Technician",
    subCategories: [
      "Heating System repair and Installation",
      "Air Conditioning Repair and Installation",
      "HVAC System Maintenance",
      "Duct Cleaning and Sealing",
      "Thermostat Installation and Repair",
      "Ventilation System Repair",
      "System upgrade and Replacement",
    ],
    isAvailable: true,
  },
  {
    name: "Adam White",
    rating: 4.1,
    completedWorks: 70,
    location: "Colombo",
    imageUrl: "assets/images/profile-1.jpg",
    category: "Elder Care Services",
    profession: "Elder Caregiver",
    subCategories: [
      "Personal Care Assistance",
      "Medication Management",
      "Companionship and Social Interaction",
      "Meal Preparation",
      "Respite Care",
    ],
    isAvailable: true,
  },
  {
    name: "Betty Black",
    rating: 4.0,
    completedWorks: 60,
    location: "Kandy",
    imageUrl: "assets/images/profile-2.jpg",
    category: "Baby Care Services",
    profession: "Babysitter",
    subCategories: [
      "Infant Care",
      "Daytime Babysitting",
      "Overnight Babysitting",
      "Meal Preparation for Children",
      "Educational and Play Activities",
    ],
    isAvailable: true,
  },
  {
    name: "Carl Green",
    rating: 4.2,
    completedWorks: 90,
    location: "Galle",
    imageUrl: "assets/images/profile-3.jpg",
    category: "House Cleaning",
    profession: "Cleaner",
    subCategories: [
      "Regular Cleaning",
      "Carpet Cleaning",
      "Window Cleaning",
      "Upholstery Cleaning",
    ],
    isAvailable: true,
  },
  {
    name: "Daisy White",
    rating: 4.4,
    completedWorks: 100,
    location: "Jaffna",
    imageUrl: "assets/images/profile-4.jpg",
    category: "Plumbing Services",
    profession: "Plumber",
    subCategories: [
      "Leak Repair",
      "Pipe Installation and and Repair",
      "Faucet and Sink Repair",
      "Water heater Repair and Installation",
      "Sewer Line Services",
    ],
    isAvailable: true,
  },
  {
    name: "Eddie Black",
    rating: 4.6,
    completedWorks: 110,
    location: "Matara",
    imageUrl: "assets/images/profile-5.jpg",
    category: "Carpentry Services",
    profession: "Carpenter",
    subCategories: [
      "Custom Cabinetry",
      "Wood Flooring Installation",
      "Trim and Molding Installation",
      "Deck Building and Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Fiona Grey",
    rating: 4.8,
    completedWorks: 150,
    location: "Jaffna",
    imageUrl: "assets/images/profile-6.jpg",
    category: "Masonry",
    profession: "Mason",
    subCategories: ["Masonry Repairs"],
    isAvailable: true,
  },
  {
    name: "George Green",
    rating: 4.7,
    completedWorks: 140,
    location: "Matara",
    imageUrl: "assets/images/profile-7.jpg",
    category: "Electrical Services",
    profession: "Electrician",
    subCategories: [
      "Electrical Wiring and Rewiring",
      "Circuit Breaker Installation",
      "Electrical Panel Upgrades",
      "Lightning Installation",
      "Generator Installation",
    ],
    isAvailable: true,
  },
  {
    name: "Hannah White",
    rating: 4.5,
    completedWorks: 120,
    location: "Kandy",
    imageUrl: "assets/images/profile-1.jpg",
    category: "Mechanic Services",
    profession: "Mechanic",
    subCategories: [
      "Engine Diagnostic and Repair",
      "Breake Services",
      "Transmission Repair",
      "Tire Services and Alignment",
      "Routine Maintenance",
      "Bodywork and collision Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Isaac Black",
    rating: 4.3,
    completedWorks: 80,
    location: "Badulla",
    imageUrl: "assets/images/profile-2.jpg",
    category: "Gardening Services",
    profession: "Gardener",
    subCategories: [
      "Lawn Care and Moving",
      "Tree Trimming nd Pruning",
      "Planting and Weeding",
      "Garden Design and Landscaping",
    ],
    isAvailable: true,
  },
  {
    name: "Jenny Grey",
    rating: 4.1,
    completedWorks: 70,
    location: "Colombo",
    imageUrl: "assets/images/profile-3.jpg",
    category: "Appliance Repair",
    profession: "Appliance Technician",
    subCategories: [
      "Refrigerator Repair",
      "Washer and Dryer Repair",
      "Small Appliance Repair",
      "Oven and Stove Repair",
    ],
    isAvailable: true,
  },
  {
    name: "Kevin Green",
    rating: 4.0,
    completedWorks: 60,
    location: "Galle",
    imageUrl: "assets/images/profile-4.jpg",
    category: "Pest Control",
    profession: "Pest Control Technician",
    subCategories: [
      "Termite Control",
      "Rodent Control",
      "Insect Extermination (ants, cockroaches)",
      "Bed Bug Treatment",
    ],
    isAvailable: true,
  },
  {
    name: "Lily White",
    rating: 4.2,
    completedWorks: 90,
    location: "Jaffna",
    imageUrl: "assets/images/profile-5.jpg",
    category: "Roofing Repair",
    profession: "Roofer",
    subCategories: [
      "Roof Installtion and Repair",
      "Roof Maintenance",
      "Roof Replacement",
      "Roof Inspections",
    ],
    isAvailable: true,
  },
  {
    name: "Mike Black",
    rating: 4.4,
    completedWorks: 100,
    location: "Matara",
    imageUrl: "assets/images/profile-6.jpg",
    category: "Gutter Repair",
    profession: "Gutter Technician",
    subCategories: [
      "Gutter Installation and Repair",
      "Gutter Cleaning",
      "Gutter Maintenance",
      "Gutter Guard Installation",
    ],
    isAvailable: true,
  },
];

async function uploadProviders() {
  try {
    await Provider.insertMany(providers);
    console.log("Providers uploaded successfully");
    mongoose.connection.close();
  } catch (error) {
    console.error("Error uploading providers:", error);
  }
}

uploadProviders();
